// Downloads the Urdu/Arabic web fonts from Google Fonts and vendors them into
// public/fonts/ so the app renders native scripts fully OFFLINE (no CDN at
// runtime). Regenerate with: npm run fetch:fonts
//
// We rewrite each @font-face `src` to a local /fonts/*.woff2 path and emit a
// self-contained stylesheet at src/styles/fonts.css.
import { mkdir, writeFile } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const here = dirname(fileURLToPath(import.meta.url))
const fontsDir = join(here, '..', 'public', 'fonts')
const cssOut = join(here, '..', 'src', 'styles', 'fonts.css')

// A modern browser UA makes Google Fonts return compact woff2.
const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36'

const FAMILIES = [
  { css: 'Noto+Nastaliq+Urdu:wght@400;700', slug: 'noto-nastaliq-urdu' },
  { css: 'Noto+Naskh+Arabic:wght@400;700', slug: 'noto-naskh-arabic' },
]

async function fetchCss(spec) {
  const url = `https://fonts.googleapis.com/css2?family=${spec}&display=swap`
  const res = await fetch(url, { headers: { 'User-Agent': UA } })
  if (!res.ok) throw new Error(`CSS fetch failed (${res.status}) for ${spec}`)
  return res.text()
}

async function main() {
  await mkdir(fontsDir, { recursive: true })
  let out = '/* Auto-generated by scripts/fetch-fonts.mjs — do not edit by hand. */\n'
  let fileIndex = 0

  for (const fam of FAMILIES) {
    const css = await fetchCss(fam.css)
    // Split into @font-face blocks and process each.
    const blocks = css.match(/@font-face\s*{[^}]*}/g) || []
    for (const block of blocks) {
      const urlMatch = block.match(/url\((https:\/\/[^)]+\.woff2)\)/)
      if (!urlMatch) continue
      const weightMatch = block.match(/font-weight:\s*(\d+)/)
      const weight = weightMatch ? weightMatch[1] : '400'
      const fileName = `${fam.slug}-${weight}-${fileIndex++}.woff2`
      const bin = await fetch(urlMatch[1], { headers: { 'User-Agent': UA } })
      if (!bin.ok) throw new Error(`font download failed ${urlMatch[1]}`)
      const buf = Buffer.from(await bin.arrayBuffer())
      await writeFile(join(fontsDir, fileName), buf)
      out += block.replace(urlMatch[0], `url(/fonts/${fileName})`) + '\n'
      console.log(`  ✓ ${fileName} (${(buf.length / 1024).toFixed(0)} KB)`)
    }
  }

  await writeFile(cssOut, out, 'utf8')
  console.log(`✓ Wrote ${cssOut}`)
}

main().catch((err) => {
  console.error('Font fetch failed:', err.message)
  process.exit(1)
})
